name: macos_haptic_feedback
description: A macOS plugin for trackpad haptic feedback
version: 1.0.0
repository: https://github.com/foamify/macos_haptic_feedback

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: MacosHapticFeedbackPlugin
